### ISSUE TITLE
ModuleNotFoundError: No module named 'myapp.views.admin'

### ISSUE THREAD

**Issue by ZhangTainan** [geeeeeeeek/python_travel#4]
按照readme，执行python manage.py runserver这一步出现如下报错
![image](https://github.com/geeeeeeeek/python_travel/assets/84077792/3d00f369-3f5c-4f21-b8c4-559f3c4e55de)

**Comment by linxi-520** [comment]
> 按照readme，执行python manage.py runserver这一步出现如下报错 ![image](https://private-user-images.githubusercontent.com/84077792/316013866-3d00f369-3f5c-4f21-b8c4-559f3c4e55de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTQ3MzUsIm5iZiI6MTcxMTExNDQzNSwicGF0aCI6Ii84NDA3Nzc5Mi8zMTYwMTM4NjYtM2QwMGYzNjktM2Y1Yy00ZjIxLWI4YzQtNTU5ZjNjNGU1NWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDEzMzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNGU1OWU0OTBlNDNmOWM0NzgxY2EzOTQ5OGM2MjM0MzZjNWZmZDYxMzQxOWZmN2IzNmUzNGVmYzljOTc4MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EV-XNHUNkKoqTf27y6mHL3u1-67pgtNXi8Z2Xeqjr5o)

未给出所有代码，付费的，我已复原所有代码。

**Comment by wsw-black** [comment]
怎么解决的 除了付费

**Comment by linxi-520** [comment]
> 怎么解决的 除了付费

我单问作者一个sql文件收费50RMB，我就自己弄的，你想不付费就自己弄，找别人帮忙不收费还是不太可能的

**Comment by wsw-black** [comment]
> > 怎么解决的 除了付费
> 
> 我单问作者一个sql文件收费50RMB，我就自己弄的，你想不付费就自己弄，找别人帮忙不收费还是不太可能的

sql文件不是项目里面有吗

**Comment by linxi-520** [comment]
> > > 怎么解决的 除了付费
> > 
> > 
> > 我单问作者一个sql文件收费50RMB，我就自己弄的，你想不付费就自己弄，找别人帮忙不收费还是不太可能的
> 
> sql文件不是项目里面有吗

之前并没有提供
